FROM openjdk:11.0.7
ADD build/libs/quiz-managment-backend-0.0.1-SNAPSHOT.jar quiz-managment-backend-0.0.1-SNAPSHOT.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "quiz-managment-backend-0.0.1-SNAPSHOT.jar"]